import {
  DEMO_VISUAL_PACK_V2_SCHEMA_VERSION,
  DESIGN_CATALOG_V2_SCHEMA_VERSION,
  DESIGN_DNA_SCHEMA_VERSION,
  DESIGN_STYLE_PRESET_V2_SCHEMA_VERSION,
  DESIGN_TEMPLATE_FAMILY_V2_SCHEMA_VERSION,
  type BlueprintPageKind,
  type BlueprintSectionV2,
  type ContentBudgetV2,
  type DesignCatalogV2Draft,
  type PageBlueprintV2,
  type SiteSpecComponentType,
} from "@global/contracts";
import { M1_E_B_B1_CATALOG_V2_DRAFT } from "./catalog-v2-b1-drafts";
import { M1_E_B_RENDERER_PRESET_TOKEN_DIGESTS } from "./renderer-preset-digests";

function section(
  id: string,
  role: string,
  componentType: SiteSpecComponentType,
  variant: string,
  contentBudgetKey: string,
  options: { assetRoles?: string[]; requiresEvidence?: boolean } = {},
): BlueprintSectionV2 {
  return {
    id,
    role,
    componentType,
    variant,
    required: true,
    requiresEvidence: options.requiresEvidence ?? false,
    assetRoles: options.assetRoles ?? [],
    contentBudgetKey,
  };
}

function blueprint(
  id: string,
  pageKind: BlueprintPageKind,
  sections: BlueprintSectionV2[],
): PageBlueprintV2 {
  return {
    id,
    pageKind,
    sections,
    mobileReflow: [
      "stack-primary-content-before-secondary-proof",
      "preserve-visible-primary-action",
    ],
  };
}

function budget(minimum: number, maximum: number): ContentBudgetV2 {
  return { minimum, maximum };
}

export const M1_E_B_B2_CATALOG_V2_DRAFT: DesignCatalogV2Draft = {
  ...M1_E_B_B1_CATALOG_V2_DRAFT,
  schemaVersion: DESIGN_CATALOG_V2_SCHEMA_VERSION,
  catalogVersion: "m1-e-b-b2-drafts/1",
  designDnas: [
    ...M1_E_B_B1_CATALOG_V2_DRAFT.designDnas,
    {
      schemaVersion: DESIGN_DNA_SCHEMA_VERSION,
      id: "oem-capability-dna",
      name: "oem-capability",
      ruleIds: ["evidence-adjacent-technical-choice"],
      hierarchy: {
        displayScale: "balanced",
        headingContrast: "high",
        maxReadingWidthRem: 44,
      },
      spatialRhythm: {
        sectionGapPx: [44, 80],
        contentGapPx: [14, 26],
        density: "balanced",
      },
      composition: {
        heroModes: ["technical", "split"],
        imageTextRatios: ["3:2", "4:3"],
        alignmentBias: "left",
      },
      surfaces: {
        cardStyle: "bordered",
        borderWeight: "strong",
        radius: "subtle",
      },
      imagery: {
        preferredSubjects: ["process", "product", "fabrication"],
        cropModes: ["contain", "cover"],
        backgroundPolicy: "mixed",
        maxGeneratedMediaRatio: 0,
      },
      motion: {
        intensity: "low",
        allowed: ["fade"],
        forbidden: ["parallax", "continuous-motion", "auto-advance"],
      },
      antiPatterns: [
        "unsupported-capability-claim",
        "decorative-production-metric",
      ],
    },
    {
      schemaVersion: DESIGN_DNA_SCHEMA_VERSION,
      id: "scientific-trust-dna",
      name: "scientific-trust",
      ruleIds: ["evidence-adjacent-technical-choice"],
      hierarchy: {
        displayScale: "balanced",
        headingContrast: "medium",
        maxReadingWidthRem: 42,
      },
      spatialRhythm: {
        sectionGapPx: [56, 96],
        contentGapPx: [16, 30],
        density: "airy",
      },
      composition: {
        heroModes: ["editorial", "technical"],
        imageTextRatios: ["4:3", "1:1"],
        alignmentBias: "mixed",
      },
      surfaces: {
        cardStyle: "flat",
        borderWeight: "hairline",
        radius: "soft",
      },
      imagery: {
        preferredSubjects: ["instrument", "sample", "validation"],
        cropModes: ["contain", "editorial_crop"],
        backgroundPolicy: "light",
        maxGeneratedMediaRatio: 0,
      },
      motion: {
        intensity: "none",
        allowed: [],
        forbidden: ["parallax", "continuous-motion", "auto-advance"],
      },
      antiPatterns: ["neon-science-theater", "unsupported-clinical-claim"],
    },
  ],
  stylePresets: [
    ...M1_E_B_B1_CATALOG_V2_DRAFT.stylePresets,
    {
      schemaVersion: DESIGN_STYLE_PRESET_V2_SCHEMA_VERSION,
      id: "oem-industrial-power",
      version: "0.1.0",
      status: "draft",
      rendererPresetId: "industrial-power",
      rendererTokenDigest: M1_E_B_B1_CATALOG_V2_DRAFT.stylePresets.find(
        (preset) => preset.rendererPresetId === "industrial-power",
      )!.rendererTokenDigest,
      defaultComponentVariants: {
        IndustrialHero: "technical-grid",
        LedgerStats: "technical-grid",
      },
    },
    {
      schemaVersion: DESIGN_STYLE_PRESET_V2_SCHEMA_VERSION,
      id: "oem-dispatch",
      version: "0.1.0",
      status: "draft",
      rendererPresetId: "dispatch",
      rendererTokenDigest: M1_E_B_RENDERER_PRESET_TOKEN_DIGESTS.dispatch,
      defaultComponentVariants: {
        DispatchHero: "quiet",
        ServicesEditorial: "technical-grid",
      },
    },
    {
      schemaVersion: DESIGN_STYLE_PRESET_V2_SCHEMA_VERSION,
      id: "scientific-biotech-minimal",
      version: "0.1.0",
      status: "draft",
      rendererPresetId: "biotech-minimal",
      rendererTokenDigest:
        M1_E_B_RENDERER_PRESET_TOKEN_DIGESTS["biotech-minimal"],
      defaultComponentVariants: {
        MinimalHero: "technical-grid",
        TrustSplit: "technical-grid",
      },
    },
    {
      schemaVersion: DESIGN_STYLE_PRESET_V2_SCHEMA_VERSION,
      id: "scientific-precision-light",
      version: "0.1.0",
      status: "draft",
      rendererPresetId: "precision-light",
      rendererTokenDigest: M1_E_B_B1_CATALOG_V2_DRAFT.stylePresets.find(
        (preset) => preset.rendererPresetId === "precision-light",
      )!.rendererTokenDigest,
      defaultComponentVariants: {
        AxiomHero: "quiet",
        CertWall: "technical-grid",
      },
    },
  ],
  demoVisualPacks: [
    ...M1_E_B_B1_CATALOG_V2_DRAFT.demoVisualPacks,
    {
      schemaVersion: DEMO_VISUAL_PACK_V2_SCHEMA_VERSION,
      id: "oem-capability-demo-pack",
      version: "0.1.0",
      status: "draft",
      compatibleFamilyIds: ["oem-capability"],
      assets: [
        {
          id: "oem-capability-hero-field",
          role: "hero",
          repositoryPath:
            "apps/site-renderer/fixtures/design-demo-visuals/oem-capability-hero.svg",
          sha256:
            "2127aec38d4a50813029eabcbf6fb6adfc6ce5e7581a7b65dbfe967785712ea0",
          mimeType: "image/svg+xml",
          altTemplate: "oem-capability-modular-manufacturing-field",
          sourceManifestId: "site-builder-demo-visual-originals",
        },
        {
          id: "oem-capability-product-module",
          role: "generic-product",
          repositoryPath:
            "apps/site-renderer/fixtures/design-demo-visuals/oem-capability-product.svg",
          sha256:
            "54180fb3c099d95bac3305eb8f70916f9e42c2bcbea2fa4a880e293cf00dbdaa",
          mimeType: "image/svg+xml",
          altTemplate: "oem-capability-generic-engineered-module",
          sourceManifestId: "site-builder-demo-visual-originals",
        },
        {
          id: "oem-capability-process-line",
          role: "generic-process",
          repositoryPath:
            "apps/site-renderer/fixtures/design-demo-visuals/oem-capability-process-line.svg",
          sha256:
            "204e76ce33159fa8d1049d37bf0e70000474cdc0580228d9fb08279dd94f3d06",
          mimeType: "image/svg+xml",
          altTemplate: "oem-capability-generic-production-sequence",
          sourceManifestId: "site-builder-demo-visual-originals",
        },
        {
          id: "oem-capability-process-proof",
          role: "generic-process",
          repositoryPath:
            "apps/site-renderer/fixtures/design-demo-visuals/oem-capability-process-proof.svg",
          sha256:
            "63304f2f21e71958cefd56b15b2d8829109db0b817ecf538af09bb27df78e0e3",
          mimeType: "image/svg+xml",
          altTemplate: "oem-capability-generic-inspection-grid",
          sourceManifestId: "site-builder-demo-visual-originals",
        },
      ],
      paletteTags: ["industrial", "process", "signal"],
      minimumContrastRatio: 4.5,
    },
    {
      schemaVersion: DEMO_VISUAL_PACK_V2_SCHEMA_VERSION,
      id: "scientific-trust-demo-pack",
      version: "0.1.0",
      status: "draft",
      compatibleFamilyIds: ["scientific-trust"],
      assets: [
        {
          id: "scientific-trust-hero-field",
          role: "hero",
          repositoryPath:
            "apps/site-renderer/fixtures/design-demo-visuals/scientific-trust-hero.svg",
          sha256:
            "974186f8c186ea0e5ec6cc0b95fa912bc552fde20b63ec30310891f6c2382464",
          mimeType: "image/svg+xml",
          altTemplate: "scientific-trust-observation-field",
          sourceManifestId: "site-builder-demo-visual-originals",
        },
        {
          id: "scientific-trust-product-instrument",
          role: "generic-product",
          repositoryPath:
            "apps/site-renderer/fixtures/design-demo-visuals/scientific-trust-product.svg",
          sha256:
            "94cb6496ee466e8bd459ead9e0cac3df0a131af96cfaf7d0de52fa1a02ab94af",
          mimeType: "image/svg+xml",
          altTemplate: "scientific-trust-generic-laboratory-instrument",
          sourceManifestId: "site-builder-demo-visual-originals",
        },
        {
          id: "scientific-trust-process-sample",
          role: "generic-process",
          repositoryPath:
            "apps/site-renderer/fixtures/design-demo-visuals/scientific-trust-process-sample.svg",
          sha256:
            "bc076be6569d4e4698ee0bceb8415f3c876ae83c233da057738d7669c44e59d4",
          mimeType: "image/svg+xml",
          altTemplate: "scientific-trust-generic-sample-workflow",
          sourceManifestId: "site-builder-demo-visual-originals",
        },
        {
          id: "scientific-trust-process-validation",
          role: "generic-process",
          repositoryPath:
            "apps/site-renderer/fixtures/design-demo-visuals/scientific-trust-process-validation.svg",
          sha256:
            "29fcd01d518118505896f6d8855ce5cf0b334dae30db4df193762e6c9a1a428f",
          mimeType: "image/svg+xml",
          altTemplate: "scientific-trust-generic-validation-matrix",
          sourceManifestId: "site-builder-demo-visual-originals",
        },
      ],
      paletteTags: ["scientific", "neutral", "evidence"],
      minimumContrastRatio: 4.5,
    },
  ],
  families: [
    ...M1_E_B_B1_CATALOG_V2_DRAFT.families,
    {
      schemaVersion: DESIGN_TEMPLATE_FAMILY_V2_SCHEMA_VERSION,
      id: "oem-capability",
      version: "0.1.0",
      status: "draft",
      designDnaId: "oem-capability-dna",
      compatibleArchetypes: ["custom-oem", "industrial-manufacturer"],
      compatibleIndustries: [
        "oem",
        "contract-manufacturing",
        "fabrication",
        "components",
      ],
      stylePresetIds: ["oem-industrial-power", "oem-dispatch"],
      blueprints: {
        home: [
          blueprint("oem-home-process", "home", [
            section(
              "oem-home-process-hero",
              "hero",
              "IndustrialHero",
              "technical-grid",
              "oem-hero",
              { assetRoles: ["hero"], requiresEvidence: true },
            ),
            section(
              "oem-home-process-stats",
              "proof",
              "LedgerStats",
              "technical-grid",
              "oem-proof",
              { requiresEvidence: true },
            ),
            section(
              "oem-home-process-systems",
              "capability",
              "TechSystems",
              "technical-grid",
              "oem-body",
              { requiresEvidence: true },
            ),
            section(
              "oem-home-process-timeline",
              "process",
              "ProcessTimeline",
              "technical-grid",
              "oem-body",
              {
                assetRoles: ["generic-process"],
                requiresEvidence: true,
              },
            ),
            section(
              "oem-home-process-projects",
              "proof",
              "ProjectsGrid",
              "technical-grid",
              "oem-body",
              { requiresEvidence: true },
            ),
            section(
              "oem-home-process-cta",
              "cta",
              "CtaBanner",
              "technical-grid",
              "oem-cta",
            ),
          ]),
          blueprint("oem-home-proof", "home", [
            section(
              "oem-home-proof-hero",
              "hero",
              "DispatchHero",
              "quiet",
              "oem-hero",
              { assetRoles: ["hero"], requiresEvidence: true },
            ),
            section(
              "oem-home-proof-trust",
              "proof",
              "TrustSplit",
              "technical-grid",
              "oem-proof",
              { requiresEvidence: true },
            ),
            section(
              "oem-home-proof-services",
              "capability",
              "ServicesEditorial",
              "technical-grid",
              "oem-body",
            ),
            section(
              "oem-home-proof-certificates",
              "proof",
              "CertWall",
              "technical-grid",
              "oem-proof",
              { requiresEvidence: true },
            ),
            section(
              "oem-home-proof-inquiry",
              "cta",
              "InquiryForm",
              "technical-grid",
              "oem-cta",
            ),
          ]),
        ],
        detail: [
          blueprint("oem-inner-capability", "inner", [
            section(
              "oem-capability-hero",
              "hero",
              "HeroBanner",
              "technical-grid",
              "oem-hero",
              { assetRoles: ["hero"], requiresEvidence: true },
            ),
            section(
              "oem-capability-features",
              "capability",
              "FeatureCards",
              "technical-grid",
              "oem-body",
            ),
            section(
              "oem-capability-materials",
              "materials",
              "MaterialsLibrary",
              "technical-grid",
              "oem-body",
              {
                assetRoles: ["generic-product"],
                requiresEvidence: true,
              },
            ),
            section(
              "oem-capability-process",
              "process",
              "ProcessSteps",
              "technical-grid",
              "oem-body",
              { requiresEvidence: true },
            ),
            section(
              "oem-capability-inquiry",
              "cta",
              "InquiryForm",
              "technical-grid",
              "oem-cta",
            ),
          ]),
          blueprint("oem-inner-quality", "inner", [
            section(
              "oem-quality-hero",
              "hero",
              "HeroBanner",
              "quiet",
              "oem-hero",
              { assetRoles: ["hero"], requiresEvidence: true },
            ),
            section(
              "oem-quality-trust",
              "proof",
              "TrustSplit",
              "technical-grid",
              "oem-proof",
              { requiresEvidence: true },
            ),
            section(
              "oem-quality-certificates",
              "proof",
              "CertWall",
              "technical-grid",
              "oem-proof",
              { requiresEvidence: true },
            ),
            section(
              "oem-quality-faq",
              "faq",
              "FaqAccordion",
              "technical-grid",
              "oem-body",
            ),
            section(
              "oem-quality-cta",
              "cta",
              "CtaCenter",
              "technical-grid",
              "oem-cta",
            ),
          ]),
        ],
      },
      safeFallbackBlueprintIds: {
        home: "oem-home-process",
        detail: "oem-inner-capability",
      },
      componentVariants: {
        IndustrialHero: ["technical-grid"],
        DispatchHero: ["quiet"],
        HeroBanner: ["technical-grid", "quiet"],
        LedgerStats: ["technical-grid"],
        TechSystems: ["technical-grid"],
        ProcessTimeline: ["technical-grid"],
        ProjectsGrid: ["technical-grid"],
        TrustSplit: ["technical-grid"],
        ServicesEditorial: ["technical-grid"],
        CertWall: ["technical-grid"],
        FeatureCards: ["technical-grid"],
        MaterialsLibrary: ["technical-grid"],
        ProcessSteps: ["technical-grid"],
        FaqAccordion: ["technical-grid"],
        InquiryForm: ["technical-grid"],
        CtaBanner: ["technical-grid"],
        CtaCenter: ["technical-grid"],
      },
      heroOptions: [
        { componentType: "IndustrialHero", variant: "technical-grid" },
        { componentType: "DispatchHero", variant: "quiet" },
      ],
      compatibilityRules: [
        { code: "requires_evidence" },
        { code: "no_adjacent_full_bleed" },
        { code: "max_consecutive_card_grid", maximum: 2 },
        { code: "max_consecutive_dark_surface", maximum: 1 },
      ],
      contentBudgets: {
        "oem-hero": budget(24, 72),
        "oem-body": budget(32, 180),
        "oem-proof": budget(12, 84),
        "oem-cta": budget(12, 48),
      },
      assetRequirements: ["hero"],
      demoVisualPackIds: ["oem-capability-demo-pack"],
      motionPolicy: {
        intensity: "low",
        allowed: ["fade"],
        forbidden: ["parallax", "continuous-motion", "auto-advance"],
      },
      qualityBaselineId: "oem-capability-draft-baseline",
      sourceManifestIds: [
        "festo-industrial-automation-study",
        "swagelok-fluid-systems-study",
        "emerson-automation-study",
      ],
      goldenFixtureIds: ["oem-capability-sparse", "oem-capability-rich"],
    },
    {
      schemaVersion: DESIGN_TEMPLATE_FAMILY_V2_SCHEMA_VERSION,
      id: "scientific-trust",
      version: "0.1.0",
      status: "draft",
      designDnaId: "scientific-trust-dna",
      compatibleArchetypes: ["equipment-supplier", "custom-oem"],
      compatibleIndustries: [
        "laboratory",
        "medical-supply",
        "instrumentation",
        "scientific-equipment",
      ],
      stylePresetIds: [
        "scientific-biotech-minimal",
        "scientific-precision-light",
      ],
      blueprints: {
        home: [
          blueprint("scientific-home-evidence", "home", [
            section(
              "scientific-home-evidence-hero",
              "hero",
              "MinimalHero",
              "technical-grid",
              "scientific-hero",
              { assetRoles: ["hero"] },
            ),
            section(
              "scientific-home-evidence-trust",
              "proof",
              "TrustSplit",
              "technical-grid",
              "scientific-proof",
              { requiresEvidence: true },
            ),
            section(
              "scientific-home-evidence-certificates",
              "proof",
              "CertWall",
              "technical-grid",
              "scientific-proof",
              { requiresEvidence: true },
            ),
            section(
              "scientific-home-evidence-products",
              "products",
              "ProductShowcaseAlt",
              "technical-grid",
              "scientific-body",
              {
                assetRoles: ["generic-product"],
                requiresEvidence: true,
              },
            ),
            section(
              "scientific-home-evidence-articles",
              "evidence",
              "ArticleGrid",
              "technical-grid",
              "scientific-body",
              { requiresEvidence: true },
            ),
            section(
              "scientific-home-evidence-inquiry",
              "cta",
              "InquiryForm",
              "technical-grid",
              "scientific-cta",
            ),
          ]),
          blueprint("scientific-home-system", "home", [
            section(
              "scientific-home-system-hero",
              "hero",
              "AxiomHero",
              "quiet",
              "scientific-hero",
              { assetRoles: ["hero"] },
            ),
            section(
              "scientific-home-system-statement",
              "statement",
              "StatementBlock",
              "technical-grid",
              "scientific-body",
            ),
            section(
              "scientific-home-system-technical",
              "capability",
              "TechSystems",
              "technical-grid",
              "scientific-body",
              { requiresEvidence: true },
            ),
            section(
              "scientific-home-system-process",
              "process",
              "ProcessTimeline",
              "technical-grid",
              "scientific-body",
              {
                assetRoles: ["generic-process"],
                requiresEvidence: true,
              },
            ),
            section(
              "scientific-home-system-cta",
              "cta",
              "CtaBanner",
              "technical-grid",
              "scientific-cta",
            ),
          ]),
        ],
        detail: [
          blueprint("scientific-inner-solution", "inner", [
            section(
              "scientific-solution-hero",
              "hero",
              "HeroBanner",
              "technical-grid",
              "scientific-hero",
              { assetRoles: ["hero"] },
            ),
            section(
              "scientific-solution-features",
              "capability",
              "FeatureCards",
              "technical-grid",
              "scientific-body",
            ),
            section(
              "scientific-solution-process",
              "process",
              "ProcessSteps",
              "technical-grid",
              "scientific-body",
              { requiresEvidence: true },
            ),
            section(
              "scientific-solution-faq",
              "faq",
              "FaqAccordion",
              "technical-grid",
              "scientific-body",
            ),
            section(
              "scientific-solution-inquiry",
              "cta",
              "InquiryForm",
              "technical-grid",
              "scientific-cta",
            ),
          ]),
          blueprint("scientific-inner-validation", "inner", [
            section(
              "scientific-validation-hero",
              "hero",
              "HeroBanner",
              "quiet",
              "scientific-hero",
              { assetRoles: ["hero"] },
            ),
            section(
              "scientific-validation-trust",
              "proof",
              "TrustSplit",
              "technical-grid",
              "scientific-proof",
              { requiresEvidence: true },
            ),
            section(
              "scientific-validation-certificates",
              "proof",
              "CertWall",
              "technical-grid",
              "scientific-proof",
              { requiresEvidence: true },
            ),
            section(
              "scientific-validation-articles",
              "evidence",
              "ArticleGrid",
              "technical-grid",
              "scientific-body",
              { requiresEvidence: true },
            ),
            section(
              "scientific-validation-cta",
              "cta",
              "CtaCenter",
              "technical-grid",
              "scientific-cta",
            ),
          ]),
        ],
      },
      safeFallbackBlueprintIds: {
        home: "scientific-home-system",
        detail: "scientific-inner-solution",
      },
      componentVariants: {
        MinimalHero: ["technical-grid"],
        AxiomHero: ["quiet"],
        HeroBanner: ["technical-grid", "quiet"],
        TrustSplit: ["technical-grid"],
        CertWall: ["technical-grid"],
        ProductShowcaseAlt: ["technical-grid"],
        ArticleGrid: ["technical-grid"],
        StatementBlock: ["technical-grid"],
        TechSystems: ["technical-grid"],
        ProcessTimeline: ["technical-grid"],
        FeatureCards: ["technical-grid"],
        ProcessSteps: ["technical-grid"],
        FaqAccordion: ["technical-grid"],
        InquiryForm: ["technical-grid"],
        CtaBanner: ["technical-grid"],
        CtaCenter: ["technical-grid"],
      },
      heroOptions: [
        { componentType: "MinimalHero", variant: "technical-grid" },
        { componentType: "AxiomHero", variant: "quiet" },
      ],
      compatibilityRules: [
        { code: "requires_evidence" },
        { code: "no_adjacent_full_bleed" },
        { code: "max_consecutive_card_grid", maximum: 2 },
        { code: "max_consecutive_dark_surface", maximum: 1 },
      ],
      contentBudgets: {
        "scientific-hero": budget(20, 68),
        "scientific-body": budget(28, 168),
        "scientific-proof": budget(12, 72),
        "scientific-cta": budget(12, 44),
      },
      assetRequirements: ["hero", "generic-product"],
      demoVisualPackIds: ["scientific-trust-demo-pack"],
      motionPolicy: {
        intensity: "none",
        allowed: [],
        forbidden: ["parallax", "continuous-motion", "auto-advance"],
      },
      qualityBaselineId: "scientific-trust-draft-baseline",
      sourceManifestIds: [
        "emerson-automation-study",
        "siemens-automation-study",
        "ifm-sensors-study",
      ],
      goldenFixtureIds: ["scientific-trust-sparse", "scientific-trust-rich"],
    },
  ],
};
