import {
  DEMO_VISUAL_PACK_V2_SCHEMA_VERSION,
  DESIGN_CATALOG_V2_SCHEMA_VERSION,
  DESIGN_DNA_SCHEMA_VERSION,
  DESIGN_STYLE_PRESET_V2_SCHEMA_VERSION,
  DESIGN_TEMPLATE_FAMILY_V2_SCHEMA_VERSION,
  type BlueprintPageKind,
  type BlueprintSectionV2,
  type ContentBudgetV2,
  type DesignCatalogV2Draft,
  type PageBlueprintV2,
  type SiteSpecComponentType,
} from "@global/contracts";
import { M1_E_B_B2_CATALOG_V2_DRAFT } from "./catalog-v2-b2-drafts";
import { M1_E_B_RENDERER_PRESET_TOKEN_DIGESTS } from "./renderer-preset-digests";

function section(
  id: string,
  role: string,
  componentType: SiteSpecComponentType,
  variant: string,
  contentBudgetKey: string,
  options: { assetRoles?: string[]; requiresEvidence?: boolean } = {},
): BlueprintSectionV2 {
  return {
    id,
    role,
    componentType,
    variant,
    required: true,
    requiresEvidence: options.requiresEvidence ?? false,
    assetRoles: options.assetRoles ?? [],
    contentBudgetKey,
  };
}

function blueprint(
  id: string,
  pageKind: BlueprintPageKind,
  sections: BlueprintSectionV2[],
): PageBlueprintV2 {
  return {
    id,
    pageKind,
    sections,
    mobileReflow: [
      "stack-primary-content-before-secondary-proof",
      "preserve-visible-primary-action",
    ],
  };
}

function budget(minimum: number, maximum: number): ContentBudgetV2 {
  return { minimum, maximum };
}

export const M1_E_B_B3_CATALOG_V2_DRAFT: DesignCatalogV2Draft = {
  ...M1_E_B_B2_CATALOG_V2_DRAFT,
  schemaVersion: DESIGN_CATALOG_V2_SCHEMA_VERSION,
  catalogVersion: "m1-e-b-b3-drafts/1",
  designDnas: [
    ...M1_E_B_B2_CATALOG_V2_DRAFT.designDnas,
    {
      schemaVersion: DESIGN_DNA_SCHEMA_VERSION,
      id: "natural-origin-dna",
      name: "natural-origin",
      ruleIds: ["evidence-adjacent-technical-choice"],
      hierarchy: {
        displayScale: "balanced",
        headingContrast: "medium",
        maxReadingWidthRem: 46,
      },
      spatialRhythm: {
        sectionGapPx: [52, 92],
        contentGapPx: [18, 32],
        density: "balanced",
      },
      composition: {
        heroModes: ["editorial", "split"],
        imageTextRatios: ["4:3", "3:2"],
        alignmentBias: "mixed",
      },
      surfaces: {
        cardStyle: "flat",
        borderWeight: "hairline",
        radius: "soft",
      },
      imagery: {
        preferredSubjects: ["material", "process", "origin"],
        cropModes: ["cover", "editorial_crop"],
        backgroundPolicy: "mixed",
        maxGeneratedMediaRatio: 0,
      },
      motion: {
        intensity: "low",
        allowed: ["fade"],
        forbidden: ["parallax", "continuous-motion", "auto-advance"],
      },
      antiPatterns: [
        "unsupported-organic-or-sustainability-claim",
        "demo-visual-presented-as-real-origin",
        "certification-without-claim-evidence",
      ],
    },
    {
      schemaVersion: DESIGN_DNA_SCHEMA_VERSION,
      id: "premium-innovation-dna",
      name: "premium-innovation",
      ruleIds: ["evidence-adjacent-technical-choice"],
      hierarchy: {
        displayScale: "editorial",
        headingContrast: "high",
        maxReadingWidthRem: 40,
      },
      spatialRhythm: {
        sectionGapPx: [64, 112],
        contentGapPx: [18, 36],
        density: "airy",
      },
      composition: {
        heroModes: ["editorial", "product_stage"],
        imageTextRatios: ["16:9", "1:1"],
        alignmentBias: "mixed",
      },
      surfaces: {
        cardStyle: "flat",
        borderWeight: "hairline",
        radius: "subtle",
      },
      imagery: {
        preferredSubjects: ["product", "material", "detail"],
        cropModes: ["contain", "editorial_crop"],
        backgroundPolicy: "dark",
        maxGeneratedMediaRatio: 0,
      },
      motion: {
        intensity: "low",
        allowed: ["fade"],
        forbidden: ["parallax", "continuous-motion", "auto-advance"],
      },
      antiPatterns: [
        "whitespace-without-product-information",
        "invented-award-client-patent-or-release",
        "unsupported-project-stat-or-testimonial",
      ],
    },
  ],
  stylePresets: [
    ...M1_E_B_B2_CATALOG_V2_DRAFT.stylePresets,
    {
      schemaVersion: DESIGN_STYLE_PRESET_V2_SCHEMA_VERSION,
      id: "natural-farmhouse",
      version: "0.1.0",
      status: "draft",
      rendererPresetId: "farmhouse",
      rendererTokenDigest: M1_E_B_RENDERER_PRESET_TOKEN_DIGESTS.farmhouse,
      defaultComponentVariants: {
        FarmhouseHero: "technical-grid",
        StoryChapters: "technical-grid",
      },
    },
    {
      schemaVersion: DESIGN_STYLE_PRESET_V2_SCHEMA_VERSION,
      id: "natural-warm-kitchen",
      version: "0.1.0",
      status: "draft",
      rendererPresetId: "warm-kitchen",
      rendererTokenDigest: M1_E_B_RENDERER_PRESET_TOKEN_DIGESTS["warm-kitchen"],
      defaultComponentVariants: {
        WarmHero: "technical-grid",
        DishesShowcase: "technical-grid",
      },
    },
    {
      schemaVersion: DESIGN_STYLE_PRESET_V2_SCHEMA_VERSION,
      id: "natural-local-trust",
      version: "0.1.0",
      status: "draft",
      rendererPresetId: "local-trust",
      rendererTokenDigest: M1_E_B_RENDERER_PRESET_TOKEN_DIGESTS["local-trust"],
      defaultComponentVariants: {
        HeroBanner: "quiet",
        TrustSplit: "technical-grid",
      },
    },
    {
      schemaVersion: DESIGN_STYLE_PRESET_V2_SCHEMA_VERSION,
      id: "premium-editorial-press",
      version: "0.1.0",
      status: "draft",
      rendererPresetId: "editorial-press",
      rendererTokenDigest:
        M1_E_B_RENDERER_PRESET_TOKEN_DIGESTS["editorial-press"],
      defaultComponentVariants: {
        EditorialHero: "technical-grid",
        StatementBlock: "technical-grid",
      },
    },
    {
      schemaVersion: DESIGN_STYLE_PRESET_V2_SCHEMA_VERSION,
      id: "premium-precision-instrument",
      version: "0.1.0",
      status: "draft",
      rendererPresetId: "precision-instrument",
      rendererTokenDigest:
        M1_E_B_RENDERER_PRESET_TOKEN_DIGESTS["precision-instrument"],
      defaultComponentVariants: {
        HeroFull: "quiet",
        ChapterShowcase: "technical-grid",
      },
    },
    {
      schemaVersion: DESIGN_STYLE_PRESET_V2_SCHEMA_VERSION,
      id: "premium-saas-cream",
      version: "0.1.0",
      status: "draft",
      rendererPresetId: "saas-cream",
      rendererTokenDigest: M1_E_B_RENDERER_PRESET_TOKEN_DIGESTS["saas-cream"],
      defaultComponentVariants: {
        HeroBanner: "quiet",
        CtaCenter: "technical-grid",
      },
    },
  ],
  demoVisualPacks: [
    ...M1_E_B_B2_CATALOG_V2_DRAFT.demoVisualPacks,
    {
      schemaVersion: DEMO_VISUAL_PACK_V2_SCHEMA_VERSION,
      id: "natural-origin-demo-pack",
      version: "0.1.0",
      status: "draft",
      compatibleFamilyIds: ["natural-origin"],
      assets: [
        {
          id: "natural-origin-hero-field",
          role: "hero",
          repositoryPath:
            "apps/site-renderer/fixtures/design-demo-visuals/natural-origin-hero.svg",
          sha256:
            "b096d1147eeb88927cb03913546c1b7be7b7776f7174759fdcca14584406d47f",
          mimeType: "image/svg+xml",
          altTemplate: "natural-origin-generic-material-landscape",
          sourceManifestId: "site-builder-demo-visual-originals",
        },
        {
          id: "natural-origin-product-samples",
          role: "generic-product",
          repositoryPath:
            "apps/site-renderer/fixtures/design-demo-visuals/natural-origin-product.svg",
          sha256:
            "d34e2938a66f3c5dd521b34cdf8bd6645bf28bbd7b90705bf8124fb155e97ff4",
          mimeType: "image/svg+xml",
          altTemplate: "natural-origin-generic-material-samples",
          sourceManifestId: "site-builder-demo-visual-originals",
        },
        {
          id: "natural-origin-process-field",
          role: "generic-process",
          repositoryPath:
            "apps/site-renderer/fixtures/design-demo-visuals/natural-origin-process-field.svg",
          sha256:
            "a19c441a1adf88af4eef1d443a6d171046d0ff26c2b21749dc471e69cdf5ba48",
          mimeType: "image/svg+xml",
          altTemplate: "natural-origin-generic-material-journey",
          sourceManifestId: "site-builder-demo-visual-originals",
        },
        {
          id: "natural-origin-process-craft",
          role: "generic-process",
          repositoryPath:
            "apps/site-renderer/fixtures/design-demo-visuals/natural-origin-process-craft.svg",
          sha256:
            "0db4b03bf326a555a109d473d182cba576ff5118af0d0aaa101ade2b3a5dfd10",
          mimeType: "image/svg+xml",
          altTemplate: "natural-origin-generic-craft-workspace",
          sourceManifestId: "site-builder-demo-visual-originals",
        },
      ],
      paletteTags: ["natural", "warm", "material"],
      minimumContrastRatio: 4.5,
    },
    {
      schemaVersion: DEMO_VISUAL_PACK_V2_SCHEMA_VERSION,
      id: "premium-innovation-demo-pack",
      version: "0.1.0",
      status: "draft",
      compatibleFamilyIds: ["premium-innovation"],
      assets: [
        {
          id: "premium-innovation-hero-stage",
          role: "hero",
          repositoryPath:
            "apps/site-renderer/fixtures/design-demo-visuals/premium-innovation-hero.svg",
          sha256:
            "9666669e209fc98603fee177f34e8d8e412a3305b79b50902a8fc839e7ff5dc7",
          mimeType: "image/svg+xml",
          altTemplate: "premium-innovation-generic-product-stage",
          sourceManifestId: "site-builder-demo-visual-originals",
        },
        {
          id: "premium-innovation-product-study",
          role: "generic-product",
          repositoryPath:
            "apps/site-renderer/fixtures/design-demo-visuals/premium-innovation-product.svg",
          sha256:
            "0f98ca44bb78c3b1cb0c0c7be689a0ff0be88f55e5900a05e6bee6955e5d6080",
          mimeType: "image/svg+xml",
          altTemplate: "premium-innovation-generic-object-study",
          sourceManifestId: "site-builder-demo-visual-originals",
        },
        {
          id: "premium-innovation-process-concept",
          role: "generic-process",
          repositoryPath:
            "apps/site-renderer/fixtures/design-demo-visuals/premium-innovation-process-concept.svg",
          sha256:
            "718d2592d584d2981bfcdcfa3041078b50d868ef432d68cc0545ea01c5f32a91",
          mimeType: "image/svg+xml",
          altTemplate: "premium-innovation-generic-concept-sequence",
          sourceManifestId: "site-builder-demo-visual-originals",
        },
        {
          id: "premium-innovation-process-proof",
          role: "generic-process",
          repositoryPath:
            "apps/site-renderer/fixtures/design-demo-visuals/premium-innovation-process-proof.svg",
          sha256:
            "c198fa382cdd8ea0679d85c9b6cf9e12097c6aa5c2f6dd36d1b9b8de6c1cef8c",
          mimeType: "image/svg+xml",
          altTemplate: "premium-innovation-generic-review-matrix",
          sourceManifestId: "site-builder-demo-visual-originals",
        },
      ],
      paletteTags: ["premium", "editorial", "precision"],
      minimumContrastRatio: 4.5,
    },
  ],
  families: [
    ...M1_E_B_B2_CATALOG_V2_DRAFT.families,
    {
      schemaVersion: DESIGN_TEMPLATE_FAMILY_V2_SCHEMA_VERSION,
      id: "natural-origin",
      version: "0.1.0",
      status: "draft",
      designDnaId: "natural-origin-dna",
      compatibleArchetypes: ["ingredient-exporter", "equipment-supplier"],
      compatibleIndustries: [
        "food-ingredient",
        "agriculture",
        "natural-material",
        "origin-product",
      ],
      stylePresetIds: [
        "natural-farmhouse",
        "natural-warm-kitchen",
        "natural-local-trust",
      ],
      blueprints: {
        home: [
          blueprint("natural-home-origin", "home", [
            section(
              "natural-home-origin-hero",
              "hero",
              "FarmhouseHero",
              "technical-grid",
              "natural-hero",
              { assetRoles: ["hero"] },
            ),
            section(
              "natural-home-origin-story",
              "story",
              "StoryChapters",
              "technical-grid",
              "natural-body",
            ),
            section(
              "natural-home-origin-materials",
              "materials",
              "MaterialsLibrary",
              "technical-grid",
              "natural-body",
              { assetRoles: ["generic-product"], requiresEvidence: true },
            ),
            section(
              "natural-home-origin-collection",
              "products",
              "CollectionCards",
              "technical-grid",
              "natural-body",
              { requiresEvidence: true },
            ),
            section(
              "natural-home-origin-cta",
              "cta",
              "CtaBanner",
              "technical-grid",
              "natural-cta",
            ),
          ]),
          blueprint("natural-home-seasonal", "home", [
            section(
              "natural-home-seasonal-hero",
              "hero",
              "WarmHero",
              "technical-grid",
              "natural-hero",
              { assetRoles: ["hero"] },
            ),
            section(
              "natural-home-seasonal-dishes",
              "products",
              "DishesShowcase",
              "technical-grid",
              "natural-body",
              { requiresEvidence: true },
            ),
            section(
              "natural-home-seasonal-featured",
              "products",
              "FeaturedSpotlight",
              "technical-grid",
              "natural-body",
              { assetRoles: ["generic-product"], requiresEvidence: true },
            ),
            section(
              "natural-home-seasonal-gallery",
              "gallery",
              "PhotoGallery",
              "technical-grid",
              "natural-body",
              { assetRoles: ["generic-process"] },
            ),
            section(
              "natural-home-seasonal-inquiry",
              "cta",
              "InquiryForm",
              "technical-grid",
              "natural-cta",
            ),
          ]),
        ],
        detail: [
          blueprint("natural-inner-catalog", "inner", [
            section(
              "natural-catalog-hero",
              "hero",
              "HeroBanner",
              "quiet",
              "natural-hero",
              { assetRoles: ["hero"] },
            ),
            section(
              "natural-catalog-products",
              "products",
              "ProductGrid",
              "technical-grid",
              "natural-body",
              { assetRoles: ["generic-product"], requiresEvidence: true },
            ),
            section(
              "natural-catalog-materials",
              "materials",
              "MaterialsLibrary",
              "technical-grid",
              "natural-body",
              { requiresEvidence: true },
            ),
            section(
              "natural-catalog-faq",
              "faq",
              "FaqAccordion",
              "technical-grid",
              "natural-body",
            ),
            section(
              "natural-catalog-cta",
              "cta",
              "CtaCenter",
              "technical-grid",
              "natural-cta",
            ),
          ]),
          blueprint("natural-inner-provenance", "inner", [
            section(
              "natural-provenance-hero",
              "hero",
              "HeroBanner",
              "technical-grid",
              "natural-hero",
              { assetRoles: ["hero"] },
            ),
            section(
              "natural-provenance-story",
              "story",
              "StoryChapters",
              "technical-grid",
              "natural-body",
            ),
            section(
              "natural-provenance-process",
              "process",
              "ProcessSteps",
              "technical-grid",
              "natural-body",
              { assetRoles: ["generic-process"], requiresEvidence: true },
            ),
            section(
              "natural-provenance-trust",
              "proof",
              "TrustSplit",
              "technical-grid",
              "natural-proof",
              { requiresEvidence: true },
            ),
            section(
              "natural-provenance-inquiry",
              "cta",
              "InquiryForm",
              "technical-grid",
              "natural-cta",
            ),
          ]),
        ],
      },
      safeFallbackBlueprintIds: {
        home: "natural-home-origin",
        detail: "natural-inner-catalog",
      },
      componentVariants: {
        FarmhouseHero: ["technical-grid"],
        WarmHero: ["technical-grid"],
        HeroBanner: ["technical-grid", "quiet"],
        StoryChapters: ["technical-grid"],
        MaterialsLibrary: ["technical-grid"],
        CollectionCards: ["technical-grid"],
        DishesShowcase: ["technical-grid"],
        FeaturedSpotlight: ["technical-grid"],
        PhotoGallery: ["technical-grid"],
        ProductGrid: ["technical-grid"],
        FaqAccordion: ["technical-grid"],
        ProcessSteps: ["technical-grid"],
        TrustSplit: ["technical-grid"],
        InquiryForm: ["technical-grid"],
        CtaBanner: ["technical-grid"],
        CtaCenter: ["technical-grid"],
      },
      heroOptions: [
        { componentType: "FarmhouseHero", variant: "technical-grid" },
        { componentType: "WarmHero", variant: "technical-grid" },
      ],
      compatibilityRules: [
        { code: "requires_evidence" },
        { code: "no_adjacent_full_bleed" },
        { code: "max_consecutive_card_grid", maximum: 2 },
        { code: "max_consecutive_dark_surface", maximum: 1 },
      ],
      contentBudgets: {
        "natural-hero": budget(20, 68),
        "natural-body": budget(28, 164),
        "natural-proof": budget(12, 72),
        "natural-cta": budget(12, 44),
      },
      assetRequirements: ["hero", "generic-product"],
      demoVisualPackIds: ["natural-origin-demo-pack"],
      motionPolicy: {
        intensity: "low",
        allowed: ["fade"],
        forbidden: ["parallax", "continuous-motion", "auto-advance"],
      },
      qualityBaselineId: "natural-origin-draft-baseline",
      sourceManifestIds: [
        "festo-industrial-automation-study",
        "emerson-automation-study",
        "ifm-sensors-study",
      ],
      goldenFixtureIds: ["natural-origin-sparse", "natural-origin-rich"],
    },
    {
      schemaVersion: DESIGN_TEMPLATE_FAMILY_V2_SCHEMA_VERSION,
      id: "premium-innovation",
      version: "0.1.0",
      status: "draft",
      designDnaId: "premium-innovation-dna",
      compatibleArchetypes: ["b2b-service", "custom-oem", "equipment-supplier"],
      compatibleIndustries: [
        "premium-equipment",
        "innovation-material",
        "design-led-b2b",
        "technology-service",
      ],
      stylePresetIds: [
        "premium-editorial-press",
        "premium-precision-instrument",
        "premium-saas-cream",
      ],
      blueprints: {
        home: [
          blueprint("premium-home-editorial", "home", [
            section(
              "premium-home-editorial-hero",
              "hero",
              "EditorialHero",
              "technical-grid",
              "premium-hero",
              { assetRoles: ["hero"] },
            ),
            section(
              "premium-home-editorial-statement",
              "statement",
              "StatementBlock",
              "technical-grid",
              "premium-body",
            ),
            section(
              "premium-home-editorial-chapter",
              "products",
              "ChapterShowcase",
              "technical-grid",
              "premium-body",
              { assetRoles: ["generic-product"], requiresEvidence: true },
            ),
            section(
              "premium-home-editorial-featured",
              "products",
              "FeaturedSpotlight",
              "technical-grid",
              "premium-body",
              { requiresEvidence: true },
            ),
            section(
              "premium-home-editorial-articles",
              "evidence",
              "ArticleGrid",
              "technical-grid",
              "premium-proof",
              { requiresEvidence: true },
            ),
            section(
              "premium-home-editorial-cta",
              "cta",
              "CtaCenter",
              "technical-grid",
              "premium-cta",
            ),
          ]),
          blueprint("premium-home-product-stage", "home", [
            section(
              "premium-home-product-hero",
              "hero",
              "HeroFull",
              "quiet",
              "premium-hero",
              { assetRoles: ["hero"] },
            ),
            section(
              "premium-home-product-showcase",
              "products",
              "ProductShowcaseAlt",
              "technical-grid",
              "premium-body",
              { assetRoles: ["generic-product"], requiresEvidence: true },
            ),
            section(
              "premium-home-product-materials",
              "materials",
              "MaterialsLibrary",
              "technical-grid",
              "premium-body",
              { requiresEvidence: true },
            ),
            section(
              "premium-home-product-projects",
              "proof",
              "ProjectsGrid",
              "technical-grid",
              "premium-proof",
              { requiresEvidence: true },
            ),
            section(
              "premium-home-product-inquiry",
              "cta",
              "InquiryForm",
              "technical-grid",
              "premium-cta",
            ),
          ]),
        ],
        detail: [
          blueprint("premium-inner-innovation", "inner", [
            section(
              "premium-innovation-hero",
              "hero",
              "HeroBanner",
              "quiet",
              "premium-hero",
              { assetRoles: ["hero"] },
            ),
            section(
              "premium-innovation-chapter",
              "products",
              "ChapterShowcase",
              "technical-grid",
              "premium-body",
              { assetRoles: ["generic-product"], requiresEvidence: true },
            ),
            section(
              "premium-innovation-systems",
              "capability",
              "TechSystems",
              "technical-grid",
              "premium-body",
              { requiresEvidence: true },
            ),
            section(
              "premium-innovation-faq",
              "faq",
              "FaqSplit",
              "technical-grid",
              "premium-body",
            ),
            section(
              "premium-innovation-cta",
              "cta",
              "CtaBanner",
              "technical-grid",
              "premium-cta",
            ),
          ]),
          blueprint("premium-inner-proof", "inner", [
            section(
              "premium-proof-hero",
              "hero",
              "HeroBanner",
              "technical-grid",
              "premium-hero",
              { assetRoles: ["hero"] },
            ),
            section(
              "premium-proof-projects",
              "proof",
              "ProjectsGrid",
              "technical-grid",
              "premium-proof",
              { requiresEvidence: true },
            ),
            section(
              "premium-proof-trust",
              "proof",
              "TrustSplit",
              "technical-grid",
              "premium-proof",
              { requiresEvidence: true },
            ),
            section(
              "premium-proof-articles",
              "evidence",
              "ArticleGrid",
              "technical-grid",
              "premium-body",
              { requiresEvidence: true },
            ),
            section(
              "premium-proof-inquiry",
              "cta",
              "InquiryForm",
              "technical-grid",
              "premium-cta",
            ),
          ]),
        ],
      },
      safeFallbackBlueprintIds: {
        home: "premium-home-editorial",
        detail: "premium-inner-innovation",
      },
      componentVariants: {
        EditorialHero: ["technical-grid"],
        HeroFull: ["quiet"],
        HeroBanner: ["technical-grid", "quiet"],
        StatementBlock: ["technical-grid"],
        ChapterShowcase: ["technical-grid"],
        FeaturedSpotlight: ["technical-grid"],
        ArticleGrid: ["technical-grid"],
        ProductShowcaseAlt: ["technical-grid"],
        MaterialsLibrary: ["technical-grid"],
        ProjectsGrid: ["technical-grid"],
        TechSystems: ["technical-grid"],
        FaqSplit: ["technical-grid"],
        TrustSplit: ["technical-grid"],
        InquiryForm: ["technical-grid"],
        CtaCenter: ["technical-grid"],
        CtaBanner: ["technical-grid"],
      },
      heroOptions: [
        { componentType: "EditorialHero", variant: "technical-grid" },
        { componentType: "HeroFull", variant: "quiet" },
      ],
      compatibilityRules: [
        { code: "requires_evidence" },
        { code: "no_adjacent_full_bleed" },
        { code: "max_consecutive_card_grid", maximum: 2 },
        { code: "max_consecutive_dark_surface", maximum: 1 },
      ],
      contentBudgets: {
        "premium-hero": budget(16, 60),
        "premium-body": budget(24, 148),
        "premium-proof": budget(12, 72),
        "premium-cta": budget(10, 40),
      },
      assetRequirements: ["hero", "generic-product"],
      demoVisualPackIds: ["premium-innovation-demo-pack"],
      motionPolicy: {
        intensity: "low",
        allowed: ["fade"],
        forbidden: ["parallax", "continuous-motion", "auto-advance"],
      },
      qualityBaselineId: "premium-innovation-draft-baseline",
      sourceManifestIds: [
        "swagelok-fluid-systems-study",
        "siemens-automation-study",
        "ifm-sensors-study",
      ],
      goldenFixtureIds: [
        "premium-innovation-sparse",
        "premium-innovation-rich",
      ],
    },
  ],
};
